=== wellingtonag/signos/dados/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="signos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="signo_aries">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_touro">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_gemeos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_cancer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_leao">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_virgem">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_libra">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_escorpiao">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_sagitario">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_capricornio">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_aquario">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signo_peixes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string" />
                            <xs:element name="data_nascimento" type="xs:string" />
                            <xs:element name="caracteristicas" type="xs:string" />
                            <xs:element name="foto" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== wellingtonag/signos/dados/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<signos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="index.xsd">

    <signo_aries>
        <nome>Aries</nome>
        <data_nascimento>21 de março a 20 de abril</data_nascimento>
        <caracteristicas>
            Áries é o primeiro signo do zodíaco e o primeiro na trilogia do fogo - simboliza a faísca. 
            É regido por Marte, o deus da guerra e das conquistas e traz em si as características de seu planeta regente. 
            Áries é impaciente, intolerante e extremamente impulsivo, primeiro atira, depois pergunta o que aconteceu. 
            As pessoas desse signo não costumam gostar de perder uma batalha, seja ela na vida prática ou emocional. 
            São pessoas individualistas e egocêntricas, gostam de dar a última palavra e de serem as primeiras, as pioneiras em todos os assuntos. 
            A pior característica desse signo é, sem dúvida, a dificuldade de amadurecer, especialmente no nível emocional - 
            são eternas crianças brigando pela atenção dos pais. Arianos e arianas são independentes, competitivos, alegres, joviais, agressivos, 
            briguentos, batalhadores, assertivos, proativos e sabem exatamente onde querem chegar. É comum encontrarmos pessoas desse signo como 
            executivos independentes e empresários.
        </caracteristicas>
        <foto>https://d15m0zxbu4pm77.cloudfront.net/icones/estudos/signos/aries/grande_aries.png</foto>
    </signo_aries>

    <signo_touro>
        <nome>Touro</nome>
        <data_nascimento>21 de abril a 20 de maio</data_nascimento>
        <caracteristicas>
            Touro é o primeiro signo do elemento terra, regido por Vênus, o planeta do amor e dos relacionamentos. 
            Touro busca segurança no amor e na vida prática, por isso é considerado o mais estável de todos os signos. 
            Touro é amoroso, afetuoso, dependente, acomodado, apaixonado e intenso. Taurinos e taurinas buscam por um trabalho
            seguro e morrem de medo de aventuras. Gostam de sentir os pés bem firmes no chão e não costumam dar passos muito largos, 
            especialmente em questões que envolvem dinheiro. São avessos a investimentos muito modernos ou que tragam qualquer risco 
            de perdas. Aliás, perda é uma palavra que faz toda e qualquer pessoa de Touro se arrepiar. 
            Estão entre os mais apegados e construtores de vínculos fortes e seguros. Touro deseja estabilidade, tanto que chega 
            a se acomodar em situações que ultrapassam a paciência de qualquer outro signo. Touro aguenta, seja o que for. Fortes e determinados, 
            não desistem até conseguirem alcançar metas e objetivos na vida pessoal e no trabalho. 
        </caracteristicas>
        <foto>https://d15m0zxbu4pm77.cloudfront.net/icones/estudos/signos/touro/grande_touro.png</foto>
    </signo_touro>

    <signo_gemeos>
        <nome>Gêmeos</nome>
        <data_nascimento>21 de maio a 20 de junho</data_nascimento>
        <caracteristicas>
            O primeiro signo de ar é Gêmeos, o signo mais curioso, apelidado de borboleta do zodíaco, pela sua curiosidade, 
            leveza e capacidade de voar de um lado a outro. Regido por Mercúrio, o deus da comunicação e do movimento, 
            traz em si a capacidade da mediação, da notícia, das trocas intelectuais e do conhecimento. Geminianos e geminianas 
            possuem como característica a rapidez das ideias e a facilidade de comunicar-se, seja com quem for. 
            Ágeis, rápidos, acelerados, ansiosos e impulsivos, são comumente encontrados no mundo dos esportes, nas agências de publicidade,
            no jornalismo e nas vendas. São dúbios, por serem dois, difíceis de lidar por conta da instabilidade e da “troca” de personalidade 
            entre um e outro de seus representantes. De fato, geminianos e geminianas tentam, mas não conseguem ser estáveis; 
            mudam de opinião e de gostos frequentemente e costumam fazer promessas que, no dia seguinte, já não conseguem cumprir. 
            Infiéis por natureza, as pessoas desse signo dificilmente conseguem construir relacionamentos com vínculos firmes e duradouros.  
        </caracteristicas>
        <foto>https://d15m0zxbu4pm77.cloudfront.net/icones/estudos/signos/gemeos/grande_gemeos.png</foto>
    </signo_gemeos>

    <signo_cancer>
        <nome>Câncer</nome>
        <data_nascimento>21 de junho a 22 de julho</data_nascimento>
        <caracteristicas>
            Câncer é o primeiro signo de água, regido pela Lua e, como seu luminar regente, é totalmente instável e pode viver as quatro fases lunares em um só dia. 
            Extremamente sensíveis e absolutamente emocionais, as pessoas desse signo sabem construir vínculos afetivos profundos e duradouros, 
            pois precisam sentir-se emocionalmente seguras em seus relacionamentos. Costumam manter as amizades por toda a vida, são aquelas pessoas que com 50 anos 
            ainda enviam presentes à melhor amiga dos primeiros anos de escola. As pessoas desse signo costumam ser fortes, apesar de mostrarem uma certa fragilidade, 
            são ligadas à segurança que a estrutura familiar traz a elas e, muitas vezes, extremamente ligadas ao trabalho e à carreira. 
            As mulheres costumam ser matriarcas, ou ao menos tentam. Já os homens costumam ser extremamente dependentes e vivem em busca de uma parceria duradoura. 
            Amam a maternidade e a paternidade e dificilmente passam pela vida sem ter filhos, mesmo que decidam não casar.   
        </caracteristicas>
        <foto>https://d15m0zxbu4pm77.cloudfront.net/icones/estudos/signos/cancer/grande_cancer.png</foto>
    </signo_cancer>

    <signo_leao>
        <nome>Leão</nome>
        <data_nascimento>23 de julho a 22 de agosto</data_nascimento>
        <caracteristicas>
            Leão é o segundo signo pertencente à trilogia do fogo e representa a chama. As pessoas de Leão são apaixonadas, possuem um ar de nobreza natural e gostam de ser
            admiradas e apreciadas. São regidos pelo Sol, o centro do Universo, e trazem em si as características de seu luminar regente. 
            Leoninos e leoninas não vivem sem uma boa paixão, precisam sentir o calor no coração. Podem ser arrogantes, altivos, egocêntricos e 
            adoram um aplauso. Nada discretos, costumam chamar a atenção de todos à sua volta, seja por conta de suas colocações firmes e seguras, de sua altivez 
            ou de sua maneira de se vestir. São entusiasmados, alegres, festivos e festeiros, indiscretos, altivos, nobres e donos da verdade. 
            Possuem uma generosidade natural para com aqueles que amam e, quando amam apaixonadamente, conseguem ser fiéis. Quando a paixão acaba, a chama começa a 
            apagar e isso pode ser um perigo para quem não sabe viver sem aplausos, sem o olhar apaixonado de seu parceiro ou parceira. 
        </caracteristicas>
        <foto>https://d15m0zxbu4pm77.cloudfront.net/icones/estudos/signos/leao/grande_leao.png</foto>
    </signo_leao>
    
    <signo_virgem>
        <nome>Virgem</nome>
        <data_nascimento>23 de agosto a 22 de setembro</data_nascimento>
        <caracteristicas>
            Virgem é o segundo signo de terra, regido por Mercúrio, o deus da comunicação e do conhecimento. Virginianos e virginianas gostam de dinheiro, 
            como todo signo de terra, mas não são escravos dele. Apreciam a segurança que o dinheiro traz e gostam, como bons representantes desse elemento, 
            de um chão firme para pisar. No entanto, possuem um lado aventureiro e amam os esportes radicais na natureza, como o alpinismo, o montanhismo, 
            as trilhas em meio à natureza, o paraquedismo, o bungee jumping, o ciclismo de montanha. o motocross e todo esporte que envolve a natureza e um pouco de perigo.
             Outra característica comum nas pessoas desse signo é o amor ao conhecimento. Todo virginiano ou virginiana têm uma biblioteca, mesmo que pequena, em sua casa. 
             É um signo que cultiva a humildade, o trabalho do dia a dia, o serviço, a construção da vida tijolo por tijolo. São simples e amam cultivar a simplicidade. 
             Discretos, fechados, reservados, emocionalmente complicados e difíceis de se entregar. A mania de limpeza, que encontramos apenas em algumas pessoas desse signo,
             tem a ver com o sentido ético, com a limpeza de caráter e da alma, que sempre cultivam.
        </caracteristicas>
        <foto>https://d15m0zxbu4pm77.cloudfront.net/icones/estudos/signos/virgem/grande_virgem.png</foto>
    </signo_virgem>

    <signo_libra>
        <nome>Libra</nome>
        <data_nascimento>23 de setembro a 22 de outubro</data_nascimento>
        <caracteristicas>
            Libra é o segundo signo do elemento ar, regido por Vênus, o planeta do amor e dos relacionamentos.
            No entanto, diferentemente de Touro, que também é regido por Vênus, não é um signo físico, é um signo em que o amor é 
            compreendido de uma maneira conceitual, no plano das ideias. Libra busca o equilíbrio e a harmonia em tudo o que toca, 
            mas isso não quer dizer que as pessoas desse signo são equilibradas; a balança, símbolo deste signo, sempre pende para um 
            lado e lá vai o libriano ou a libriana tentar equilibrá-la. Alguns autores e eu estou entre eles, consideram Libra um ariano 
            bem educado, que envernizou suas atitudes para serem aceitas socialmente. Aliás, o maior problema das pessoas desse signo é a 
            aceitação, por isso a dificuldade em fazer escolhas, em tomar partido, em pender para um dos lados da balança. Librianos e librianas, 
            são gentis, amáveis, odeiam brigas e mal-entendidos, mas quando perdem a paciência, tornam-se agressivos e até mesmo violentos,
